blender_version_min = "4.4.0"
id = "SaitoTsutomu_StarrySky"
license = ["SPDX:MIT"]
maintainer = "Saito Tsutomu <tsutomu7@hotmail.co.jp>"
name = "StarrySky"
schema_version = "1.0.0"
tagline = "Create starry sky."
type = "add-on"
version = "1.0.0"
website = "https://github.com/SaitoTsutomu/StarrySky/"
